Repository jenkinsci/lib-crypto-util, pull requests merged in 2020-04, with the labels that each got.

#5 Add CI + fix test + update pom + release drafter
  .github/release-drafter.yml
  .github/workflow/release-drafter.yml
  .gitignore
  Jenkinsfile
  get-cert.sh
  pom.xml
  src/test/resources/org/jvnet/hudson/crypto/site.crt
  src/test/resources/org/jvnet/hudson/crypto/sun.crt
Labels: chore

#6 Fix github action path
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#9 Replace Jenkinsfile by a library Jenkinsfile template
  Jenkinsfile
  pom.xml
Labels: chore

#7 Create README
  README.md
Labels: documentation

#1 update commons-codec from 1.8 to 1.12
  pom.xml
Labels: dependencies

#8 Specify default charset for string and byte calls
  pom.xml
  src/main/java/org/jvnet/hudson/crypto/RSAPublicKeyUtil.java
Labels: bugfix

#10 Add Jenkins repository for parent pom
  pom.xml
Labels: chore
